services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # map host port only if you need host access; avoid 5432 if host uses it
    ports:
      - "5435:5432"

  web:
    build: .
    restart: unless-stopped   #this line was not in suggession
    env_file:
      - ./.env
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: ${POSTGRES_DB}
      DJANGO_DB_USER: ${POSTGRES_USER}
      DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_DB_PORT: "5432"
      # DEBUG, SECRET_KEY, ALLOWED_HOSTS come from .env    
    volumes:
      - static_volume:/app/staticfiles        # share static files with nginx
                                  # internal port only
    depends_on:
      db:
        condition: service_healthy
    command: >
       gunicorn --bind 0.0.0.0:9000 src.wsgi:application --workers 3 
       --timeout 120 --access-logfile - --error-logfile -
    expose:
      - "9000"  
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"   # optional, only if you configure TLS later
    volumes:
      - static_volume:/usr/share/nginx/html/static:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

volumes:
  postgres_data:
  static_volume: