# Generated by Django 4.2.20 on 2025-04-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicechequemap',
            name='credit_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_allocations', to='cheques.creditinvoice'),
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
        migrations.AlterModelTable(
            name='creditinvoice',
            table='credit_invoice',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='customerpayment',
            table='customer_payment',
        ),
    ]
