# Generated by Django 4.2.20 on 2025-04-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicechequemap',
            old_name='creditinvoice',
            new_name='credit_invoice',
        ),
        migrations.AlterField(
            model_name='chequestore',
            name='cheque_detail',
            field=models.TextField(blank=True, default=''),
        ),
    ]
