# Generated by Django 5.1.6 on 2025-03-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_claimcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimcategory',
            old_name='catatory_name',
            new_name='category_name',
        ),
    ]
