# Generated by Django 4.2.20 on 2025-04-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_chequestore_insturment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequestore',
            name='insturment_type',
        ),
    ]
