# Generated by Django 4.2.20 on 2025-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0003_remove_chequestore_insturment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequestore',
            name='insturment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Cheque'), (3, 'Demand Draft'), (4, 'EFT'), (5, 'RTGS')], default=2),
        ),
    ]
