# Generated by Django 4.2.20 on 2025-04-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0005_rename_insturment_type_chequestore_instrument_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chequestore',
            old_name='cheque_no',
            new_name='receipt_no',
        ),
    ]
