# Generated by Django 4.2.20 on 2025-04-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0006_rename_cheque_no_chequestore_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclaim',
            name='last_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='masterclaim',
            name='prefix',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='chequestore',
            name='instrument_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Cheque'), (3, 'Pay Order'), (4, 'EFT'), (5, 'RTGS')], default=2),
        ),
    ]
