# Generated by Django 4.2.20 on 2025-04-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0007_masterclaim_last_number_masterclaim_prefix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterclaim',
            old_name='last_number',
            new_name='next_number',
        ),
    ]
