# Generated by Django 5.1.6 on 2025-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0007_customerclaim_claim_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerclaim',
            name='claim_date',
            field=models.DateField(null=True),
        ),
    ]
