# Generated by Django 4.2.20 on 2025-05-03 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0008_rename_last_number_masterclaim_next_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicechequemap',
            name='adjusted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoiceclaimmap',
            name='adjusted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='masterclaim',
            name='next_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
