# Generated by Django 4.2.20 on 2025-05-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0009_invoicechequemap_adjusted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceclaimmap',
            name='credit_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_allocations', to='cheques.creditinvoice'),
        ),
    ]
