# Generated by Django 4.2.20 on 2025-05-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0010_alter_invoiceclaimmap_credit_invoice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masterclaim',
            table='master_claim',
        ),
    ]
